### ISSUE TITLE
Cables Disconnecting on Restart

### ISSUE THREAD

**Issue by Oraiz** [ruifung/MECapabilityAdapter#2]
Playing Enigmatica 2 Expert: Skyblock 1.16a (with this mod added), and have mob farms etc set up in compact machines, but the ME Capability Adaptor disconnects when starting the game. 
Breaking and replacing works, but doesn't work remotely (block-breakers etc).

This didn't happen in previous versions of the modpack, but I can't remember which version I updated from!

**Comment by ruifung** [comment]
What version of AE2? RV6?

Also note that I don't have that much time for minecraft lately, but if anyone sends me a PR, i'll look at it.
Otherwise, I'll take a look at this when I have time to.

**Comment by PizzaAddict** [comment]
I think block update is not happening properly. causing block update by any method re-connects disconnected cables/energy cells/etc.
Can you make a small adjustment which causes block update automatically when the chunk/compact machine is loaded?

**Comment by clear1116** [comment]
If player set the same side to link compact machine ,the cable will disconnect when starting the game and crossing dimensions
