### ISSUE TITLE
Crafting recipe breaks with AE2 channels disabled

### ISSUE THREAD

**Issue by KollinsPlays** [ruifung/MECapabilityAdapter#3]
When disabling the channels in AE2 config via networkfeatures { B:Channels=false ] the recipe for adapters breaks because it uses a dense cable that won't be available with channels disabled.

Please add some way to have the mod detect this setting in the AE2 config and adjust the recipe so users can add this mod to a pack with channels disabled without having to build a crafttweaker script recipe.

When I added this mod to Skyfactory 4-4.1.0 Minecraft 1.12.2 the dense cable shows as a disabled item, whether in prestige mode or not. I verified by adding this mod to a custom test 1.12.2 modpack and with AE2 channels enabled the recipe works normally, but if I exit the game, change the AE2 config to channels disabled and load it back up, I get the same recipe disabled icon where the dense cable would be.

**Comment by ruifung** [comment]
It is unlikely that I will have time to look into how to make conditional JSON receipes like that any time soon. PR's are welcome thogugh.

**Comment by KollinsPlays** [comment]
I have enough programming knowledge to make reasonable feature requests and know what a conditional JSON recipe is, but not how to write one. I had to look up what a PR is. What about a compromise to use something else for the recipe, like a Compact Machines Tunnel, or an ME Interface or something you can make whether or not channels are enabled?

**Comment by ruifung** [comment]
Fixed in #4
